POST http://localhost:3001/registerEstabelecimento HTTP/1.1
content-type: application/json


{
    "cnpj": "12312312311234",
    "nomeOrganizacao": "pedro",
    "email": "breneerestudos@gmail.com",
    "endereco": "dsfsdfds22",
    "cidade": "cidadfdfds22de",
    "horariosFuncionamento": "df22f",
    "possuiParceiros": "sd22fdf",
    "senha": "123123123",
}   